修改拉取镜像出错时，无法继续拉取其他镜像的问题

diff --git a/.github/workflows/docker.yaml b/.github/workflows/docker.yaml
--- a/.github/workflows/docker.yaml
+++ b/.github/workflows/docker.yaml
@@ -107,7 +107,10 @@ jobs:
             fi
         
             echo "docker pull $line"
-            docker pull $line
+            docker pull $line  || {
+                echo "Failed to pull $line, continuing with next image..."
+                continue
+            }
             platform=$(echo "$line" | awk -F'--platform[ =]' '{if (NF>1) print $2}' | awk '{print $1}')
             echo "platform is $platform"
             # 如果存在架构信息 将架构信息拼到镜像名称前面
